/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana principal de gestión de viviendas. Muestra todas las propiedades
 * registradas en una tabla con sus datos de identificación, ubicación,
 * características físicas y estado. Permite buscar, registrar nuevas viviendas,
 * editar y eliminar.
 *
 * @author Diego
 * @version 1.0
 */
public class DlgMainVivienda extends javax.swing.JDialog {

    /**
     * Crea la ventana principal de administración de viviendas. Inicializa los
     * componentes gráficos, centra la ventana en pantalla, asigna el título y
     * carga automáticamente la tabla con todos los registros.
     *
     * @param parent Ventana padre que invoca este diálogo
     * @param modal Si es modal, bloquea la ventana padre hasta cerrar
     */
    public DlgMainVivienda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Gestión de Vivienda");
        cargarTabla();
    }

    /**
     * Carga y muestra todas las viviendas registradas en la tabla. Define las
     * columnas con los datos de identificación, ubicación, medidas,
     * características y estado. Recorre la lista completa y llena cada fila.
     * Muestra también la cantidad total de registros.
     */
    // ==== CARGAR TABLA ====
    private void cargarTabla() {
        // Definir nombres de las columnas que se mostrarán en la tabla
        String[] columnas = {"ID", "Descripción", "Dirección", "M² Construc",
            "M² Lote", "Tipo", "Habitaciones", "Precio Base", "Estado"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);

        for (logica.Vivienda viv : datos.GuanaRent.listaViviendas) {
            Object[] fila = {
                viv.getIdVivienda(),
                viv.getDescripcion(),
                viv.getDireccion(),
                viv.getMtsConstruct(),
                viv.getMtsLote(),
                viv.getTipoConstruccion(),
                viv.getCantHabitac(),
                viv.getPrecioBase(),
                viv.getEstado()
            };
            modelo.addRow(fila);
        }

        tblViviendas.setModel(modelo);
        txtCantViviendas.setText(String.valueOf(datos.GuanaRent.listaViviendas.size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCantViviendas = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViviendas = new javax.swing.JTable();
        lblCantPropietarios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Viviendas");

        txtCantViviendas.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblBuscar.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblBuscar.setText("Buscar:");

        txtBuscar.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnInsertar.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setHideActionText(true);
        btnInsertar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInsertar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnInsertar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnInsertar)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInsertar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tblViviendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblViviendas);

        lblCantPropietarios.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblCantPropietarios.setText("Cant.Viviendas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCantPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantPropietarios)
                    .addComponent(txtCantViviendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Abre la ventana para registrar una nueva vivienda. Al cerrar la ventana
     * de registro, recarga la tabla para mostrar automáticamente el nuevo
     * registro agregado.
     *
     * @param evt Evento de acción al presionar el botón Insertar
     */
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        DlgNewVivienda dlg = new DlgNewVivienda((java.awt.Frame) this.getParent(), true);
        dlg.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_btnInsertarActionPerformed
    /**
     * Abre la ventana para modificar los datos de la vivienda seleccionada.
     * Verifica que se haya seleccionado una fila, obtiene el identificador,
     * busca el objeto en la lista y abre la ventana en modo edición. Al cerrar,
     * actualiza la tabla con los cambios.
     *
     * @param evt Evento de acción al presionar el botón Editar
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tblViviendas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una vivienda de la tabla");
            return;
        }
        String id = tblViviendas.getValueAt(fila, 0).toString();

        logica.Vivienda seleccionada = null;
        for (logica.Vivienda viv : datos.GuanaRent.listaViviendas) {
            if (viv.getIdVivienda().equals(id)) {
                seleccionada = viv;
                break;
            }
        }

        if (seleccionada != null) {
            DlgNewVivienda dlg = new DlgNewVivienda(
                    (java.awt.Frame) this.getParent(), true, seleccionada);
            dlg.setVisible(true);
            cargarTabla();
        }

    }//GEN-LAST:event_btnEditarActionPerformed
    /**
     * Elimina la vivienda seleccionada tras confirmación del usuario. Verifica
     * la selección, obtiene el identificador, pide confirmación, elimina de la
     * lista y recarga la tabla. Muestra mensaje de confirmación.
     *
     * @param evt Evento de acción al presionar el botón Eliminar
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblViviendas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una vivienda de la tabla");
            return;
        }
        String id = tblViviendas.getValueAt(fila, 0).toString();

        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Eliminar la vivienda con ID: " + id + "?",
                "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            logica.Vivienda eliminar = null;
            for (logica.Vivienda viv : datos.GuanaRent.listaViviendas) {
                if (viv.getIdVivienda().equals(id)) {
                    eliminar = viv;
                    break;
                }
            }
            if (eliminar != null) {
                datos.GuanaRent.listaViviendas.remove(eliminar);
                JOptionPane.showMessageDialog(this, "Vivienda Eliminada");
                cargarTabla();
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed
    /**
     * Filtra y muestra en la tabla solo las viviendas que coincidan con el
     * texto ingresado. Busca por identificador, descripción o dirección,
     * ignorando mayúsculas y minúsculas.
     *
     * @param evt Evento al presionar Enter en el campo de búsqueda
     */
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        String buscar = txtBuscar.getText().trim().toLowerCase();
        String[] columnas = {"ID", "Descripción", "Dirección", "M² Construc",
            "M² Lote", "Tipo", "Habitaciones", "Precio Base", "Estado"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);

        // Filtrar por ID, Descripción o Dirección
        for (logica.Vivienda viv : datos.GuanaRent.listaViviendas) {
            if (viv.getIdVivienda().toLowerCase().contains(buscar)
                    || viv.getDescripcion().toLowerCase().contains(buscar)
                    || viv.getDireccion().toLowerCase().contains(buscar)) {

                modelo.addRow(new Object[]{
                    viv.getIdVivienda(),
                    viv.getDescripcion(),
                    viv.getDireccion(),
                    viv.getMtsConstruct(),
                    viv.getMtsLote(),
                    viv.getTipoConstruccion(),
                    viv.getCantHabitac(),
                    viv.getPrecioBase(),
                    viv.getEstado()
                });
            }
        }

        tblViviendas.setModel(modelo);
        txtCantViviendas.setText(String.valueOf(modelo.getRowCount()));

    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgMainVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgMainVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgMainVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgMainVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgMainVivienda dialog = new DlgMainVivienda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCantPropietarios;
    private javax.swing.JTable tblViviendas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantViviendas;
    // End of variables declaration//GEN-END:variables
}
