/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import logica.Alquiler;
import logica.Inquilino;
import logica.Vivienda;

/**
 *
 * @author Deilyn Medrano
 * @author Erry - Interfaz Terminada
 */
public class DlgNewAlquileres extends javax.swing.JDialog {

   private Alquiler alquiler;
    private int operacion;
    /**
     * Creates new form DlgNewAlquileres
     * @param parent
     * @param modal
     */
    public DlgNewAlquileres(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    operacion = 0;

    txtNAlquiler.setText(
            String.valueOf(datos.GuanaRent.contAlquiler));

    txtEstado.setText("Vigente");
    txtEstado.setEditable(false);

    dtpFechaContrato.setDate(LocalDate.now());
      
    }

    public DlgNewAlquileres(java.awt.Frame parent, boolean modal,
        Alquiler alquiler) {

    super(parent, modal);
    initComponents();

    setLocationRelativeTo(null);
    setTitle("Modificar Alquiler");

    this.alquiler = alquiler;
    operacion = 1;

    cargarDatos();
}
    private void cargarDatos() {

    if (alquiler == null) {
        return;
    }

    txtNAlquiler.setText(
            String.valueOf(alquiler.getNumAlquiler()));

    dtpFechaContrato.setDate(
            alquiler.getFechContrato());

    txtCantMeses.setText(
            String.valueOf(alquiler.getCantMeses()));

    txtCantAdultos.setText(
            String.valueOf(alquiler.getNumAdultos()));

    txtCantNinos.setText(
            String.valueOf(alquiler.getNumNinos()));

    txtDeposiGarantia.setText(
            String.valueOf(alquiler.getDepositoGarantia()));

    txtPrecioAlqui.setText(
            String.valueOf(alquiler.getPrecioAlquiler()));

    txtIncreAnual.setText(
            String.valueOf(alquiler.getPorcIncremAnual()));

    if (alquiler.getInquilino() != null) {
        txtInquilino.setText(
                alquiler.getInquilino().getCedInqui());
    }

    if (alquiler.getVivienda() != null) {
        txtVivienda.setText(
                alquiler.getVivienda().getIdVivienda());
    }

    txtEstado.setText(alquiler.getEstado());

    txtNAlquiler.setEnabled(false);
    txtEstado.setEditable(false);
}
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNAlquiler = new javax.swing.JLabel();
        txtNAlquiler = new javax.swing.JTextField();
        lblFechaContrato = new javax.swing.JLabel();
        dtpFechaContrato = new com.github.lgooddatepicker.components.DatePicker();
        lblCantMeses = new javax.swing.JLabel();
        txtCantMeses = new javax.swing.JTextField();
        lblCantAdultos = new javax.swing.JLabel();
        txtCantAdultos = new javax.swing.JTextField();
        lblCantNinos = new javax.swing.JLabel();
        txtCantNinos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblDeposiGarantia = new javax.swing.JLabel();
        lblPrecioAlqui = new javax.swing.JLabel();
        lblIncreAnual = new javax.swing.JLabel();
        txtDeposiGarantia = new javax.swing.JTextField();
        txtPrecioAlqui = new javax.swing.JTextField();
        txtIncreAnual = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblInquilino = new javax.swing.JLabel();
        lblVivienda = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtInquilino = new javax.swing.JTextField();
        txtVivienda = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        btnBuscarInquilino = new javax.swing.JButton();
        btnBuscarVivienda = new javax.swing.JButton();
        btnBuscarEstado = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Regristrar Nuevo Alquiler");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registrar Nuevo Alquiler", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 12))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNAlquiler.setText("N° Alquiler:");
        lblNAlquiler.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        txtNAlquiler.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        txtNAlquiler.setEnabled(false);

        lblFechaContrato.setText("Fecha Contrato:");
        lblFechaContrato.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        lblCantMeses.setText("Cant.Meses:");
        lblCantMeses.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        txtCantMeses.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        lblCantAdultos.setText("Adultos:");
        lblCantAdultos.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        txtCantAdultos.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        lblCantNinos.setText("Niños:");
        lblCantNinos.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        txtCantNinos.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(lblNAlquiler)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCantMeses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaContrato, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dtpFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(294, 294, 294))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCantNinos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCantAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantNinos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantAdultos)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNAlquiler)
                            .addComponent(txtNAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaContrato)
                            .addComponent(dtpFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantMeses)
                            .addComponent(txtCantMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantNinos)
                            .addComponent(txtCantNinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDeposiGarantia.setText("Depósito Garantía:");
        lblDeposiGarantia.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        lblPrecioAlqui.setText("Precio Alquiler:");
        lblPrecioAlqui.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        lblIncreAnual.setText("% Incremento Anual:");
        lblIncreAnual.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        txtDeposiGarantia.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        txtPrecioAlqui.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        txtIncreAnual.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeposiGarantia)
                            .addComponent(lblPrecioAlqui, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecioAlqui, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(txtDeposiGarantia)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblIncreAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIncreAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeposiGarantia)
                    .addComponent(txtDeposiGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioAlqui)
                    .addComponent(txtPrecioAlqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIncreAnual)
                    .addComponent(txtIncreAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblInquilino.setText("Inquilino:");
        lblInquilino.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        lblVivienda.setText("Vivienda:");
        lblVivienda.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        lblEstado.setText("Estado:");
        lblEstado.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        txtInquilino.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        txtVivienda.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        txtEstado.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N

        btnBuscarInquilino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscarInquilino.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        btnBuscarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInquilinoActionPerformed(evt);
            }
        });

        btnBuscarVivienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscarVivienda.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        btnBuscarVivienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarViviendaActionPerformed(evt);
            }
        });

        btnBuscarEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscarEstado.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        btnBuscarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVivienda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVivienda, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarVivienda)
                            .addComponent(btnBuscarEstado)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarInquilino)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblInquilino))
                            .addComponent(btnBuscarInquilino))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVivienda)))
                    .addComponent(btnBuscarVivienda))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEstado)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarEstado))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {

    LocalDate fecha = dtpFechaContrato.getDate();

    if (fecha == null) {
        JOptionPane.showMessageDialog(
                this,
                "Seleccione la fecha del contrato.");
        return;
    }

    int meses = Integer.parseInt(
            txtCantMeses.getText().trim());

    int adultos = Integer.parseInt(
            txtCantAdultos.getText().trim());

    int ninos = Integer.parseInt(
            txtCantNinos.getText().trim());

    double deposito = Double.parseDouble(
            txtDeposiGarantia.getText().trim());

    double precio = Double.parseDouble(
            txtPrecioAlqui.getText().trim());

    double incremento = Double.parseDouble(
            txtIncreAnual.getText().trim());

    String cedula = txtInquilino.getText().trim();
    String idVivienda = txtVivienda.getText().trim();

    Inquilino inquilino =
            datos.GuanaRent.buscarInquilinoCed(cedula);

    Vivienda vivienda =
            datos.GuanaRent.buscarViviendaID(idVivienda);

    if (inquilino == null) {
        JOptionPane.showMessageDialog(
                this,
                "El inquilino no existe.");
        return;
    }

    if (vivienda == null) {
        JOptionPane.showMessageDialog(
                this,
                "La vivienda no existe.");
        return;
    }

    if (operacion == 0) {

        Alquiler nuevo = new Alquiler(
                0,
                fecha,
                meses,
                adultos,
                ninos,
                deposito,
                precio,
                incremento,
                inquilino,
                vivienda,
                "Vigente"
        );

        if (datos.GuanaRent.agregarAlquiler(nuevo)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Alquiler guardado correctamente.");

            dispose();
        }

    } else {

        Alquiler nuevo = new Alquiler(
                alquiler.getNumAlquiler(),
                fecha,
                meses,
                adultos,
                ninos,
                deposito,
                precio,
                incremento,
                inquilino,
                vivienda,
                alquiler.getEstado()
        );

        if (datos.GuanaRent.modificarAlquiler(
                alquiler.getNumAlquiler(), nuevo)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Alquiler modificado correctamente.");

            dispose();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo modificar el alquiler.");
        }
    }

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
            this,
            "Ingrese valores numéricos válidos.");

} catch (Exception e) {

    JOptionPane.showMessageDialog(
            this,
            "Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        if (operacion == 0) {

    txtCantMeses.setText("");
    txtCantAdultos.setText("");
    txtCantNinos.setText("");
    txtDeposiGarantia.setText("");
    txtPrecioAlqui.setText("");
    txtIncreAnual.setText("");
    txtInquilino.setText("");
    txtVivienda.setText("");

    txtEstado.setText("Vigente");

    dtpFechaContrato.setDate(
            LocalDate.now());

} else {

    cargarDatos();
}
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInquilinoActionPerformed
        String cedula = JOptionPane.showInputDialog(
        this,
        "Ingrese la cédula del inquilino:");

if (cedula == null || cedula.trim().isEmpty()) {
    return;
}

Inquilino inquilino =
        datos.GuanaRent.buscarInquilinoCed(
                cedula.trim());

if (inquilino == null) {

    JOptionPane.showMessageDialog(
            this,
            "El inquilino no existe.");

} else {

    txtInquilino.setText(
            inquilino.getCedInqui());

    JOptionPane.showMessageDialog(
            this,
            "Inquilino encontrado.");
}
    }//GEN-LAST:event_btnBuscarInquilinoActionPerformed

    private void btnBuscarViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarViviendaActionPerformed
        String id = JOptionPane.showInputDialog(
        this,
        "Ingrese el ID de la vivienda:");

if (id == null || id.trim().isEmpty()) {
    return;
}

Vivienda vivienda =
        datos.GuanaRent.buscarViviendaID(
                id.trim());

if (vivienda == null) {

    JOptionPane.showMessageDialog(
            this,
            "La vivienda no existe.");

} else {

    txtVivienda.setText(
            vivienda.getIdVivienda());

    JOptionPane.showMessageDialog(
            this,
            "Vivienda encontrada.");
}
    }//GEN-LAST:event_btnBuscarViviendaActionPerformed

    private void btnBuscarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstadoActionPerformed
        txtEstado.setText("Vigente");
    }//GEN-LAST:event_btnBuscarEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgNewAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgNewAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgNewAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgNewAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgNewAlquileres dialog = new DlgNewAlquileres(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEstado;
    private javax.swing.JButton btnBuscarInquilino;
    private javax.swing.JButton btnBuscarVivienda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private com.github.lgooddatepicker.components.DatePicker dtpFechaContrato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCantAdultos;
    private javax.swing.JLabel lblCantMeses;
    private javax.swing.JLabel lblCantNinos;
    private javax.swing.JLabel lblDeposiGarantia;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaContrato;
    private javax.swing.JLabel lblIncreAnual;
    private javax.swing.JLabel lblInquilino;
    private javax.swing.JLabel lblNAlquiler;
    private javax.swing.JLabel lblPrecioAlqui;
    private javax.swing.JLabel lblVivienda;
    private javax.swing.JTextField txtCantAdultos;
    private javax.swing.JTextField txtCantMeses;
    private javax.swing.JTextField txtCantNinos;
    private javax.swing.JTextField txtDeposiGarantia;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIncreAnual;
    private javax.swing.JTextField txtInquilino;
    private javax.swing.JTextField txtNAlquiler;
    private javax.swing.JTextField txtPrecioAlqui;
    private javax.swing.JTextField txtVivienda;
    // End of variables declaration//GEN-END:variables
}
